from enum import StrEnum


class IntegrationProvider(StrEnum):
    WHATSAPP_CLOUD_API = "WHATSAPP_CLOUD_API"
    INSTAGRAM_BUSINESS = "INSTAGRAM_BUSINESS"
    FACEBOOK_PAGE = "FACEBOOK_PAGE"
    SMTP_EMAIL = "SMTP_EMAIL"
    GOOGLE_CLOUD_STORAGE = "GOOGLE_CLOUD_STORAGE"
    AWS_S3 = "AWS_S3"


class IntegrationStatus(StrEnum):
    CONNECTED = "CONNECTED"
    DISCONNECTED = "DISCONNECTED"
    EXPIRED = "EXPIRED"
    ERROR = "ERROR"
