from enum import StrEnum


class ServiceType(StrEnum):
    MATERNITY = "MATERNITY"
    NEWBORN = "NEWBORN"
    FAMILY = "FAMILY"
    MILESTONE = "MILESTONE"
    CAKE_SMASH = "CAKE_SMASH"


class BookingStatus(StrEnum):
    PENDING_ADVANCE = "PENDING_ADVANCE"
    CONFIRMED = "CONFIRMED"
    SCHEDULED = "SCHEDULED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class BookingItemStatus(StrEnum):
    PENDING = "PENDING"
    SCHEDULED = "SCHEDULED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ShootStatus(StrEnum):
    NOT_SCHEDULED = "NOT_SCHEDULED"
    SCHEDULED = "SCHEDULED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    RESCHEDULED = "RESCHEDULED"
    CANCELLED = "CANCELLED"


class AssignmentRole(StrEnum):
    LEAD_PHOTOGRAPHER = "LEAD_PHOTOGRAPHER"
    SECOND_PHOTOGRAPHER = "SECOND_PHOTOGRAPHER"
    ASSISTANT = "ASSISTANT"
