from enum import StrEnum


class GalleryStatus(StrEnum):
    DRAFT = "DRAFT"
    UPLOADED = "UPLOADED"
    SELECTION_OPEN = "SELECTION_OPEN"
    SELECTION_SUBMITTED = "SELECTION_SUBMITTED"
    SELECTION_REOPENED = "SELECTION_REOPENED"
    SELECTION_CLOSED = "SELECTION_CLOSED"
